name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Test File
      run: |
        cd API-TEST
        docker build -t chrismerkle19/tcmg412-test-file .
      
    - name: Build API
      run: |
        cd api
        docker build -t chrismerkle19/tcmg412-api .
    
    - name: Docker compose
      run: |
        cd api
        docker-compose build
        docker-compose up -d
    
    - name: Docker ps
      run: docker ps
    
    - name: Test Code
      run: |
        cd api
    
    - name: Pushing image
      run: |
        docker login -u ${{ secrets.dockerusername}} -p ${{ secrets.dockerpassword}}
        docker image tag chrismerkle19/tcmg412-api chrismerkle19/tcmg412-api:latest
        docker image tag chrismerkle19/tcmg412-api chrismerkle19/tcmg412-api:$(date +%s)
        docker image push --all-tags chrismerkle19/tcmg412-api
